services:
  - type: web
    name: plain-slack-integration-production
    env: node
    repo: https://github.com/krivachy/plain-slack-integration.git
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: npm install -g pnpm && pnpm i && pnpm build
    startCommand: node dist/app.js
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: BASE_DOMAIN
        value: https://plain-slack-integration-production.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: SLACK_CLIENT_ID
        value: 5201178479941.5226688564182
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
  - type: web
    name: plain-slack-integration-development
    env: node
    repo: https://github.com/krivachy/plain-slack-integration.git
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: npm install -g pnpm && pnpm i && pnpm build
    startCommand: node dist/app.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: BASE_DOMAIN
        value: https://plain-slack-integration-development.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: SLACK_CLIENT_ID
        value: 5201178479941.5211681684117
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false